### ISSUE TITLE
215 Issue with Payload Data

### ISSUE THREAD

**Issue by werdnum** [printpal-io/OctoPrint-PrintWatch#11]
I noticed that the PrintWatch tab is empty and a failed print wasn't correctly aborted.

When I looked through logs, I found the following:

```
.octoprint/logs/octoprint.log.2022-02-06:2022-02-07 09:48:49,062 - octoprint.plugins.printwatch - INFO - Response: {'response': 'Issue with payload data', 'statusCode': 215}
.octoprint/logs/octoprint.log.2022-02-06:2022-02-07 09:48:59,933 - octoprint.plugins.printwatch - INFO - Payload: {'api_key': 'XXX', 'enable_shutoff': True, 'stream_url': 'http://192.168.124.210/webcam/?action=stream'} {'last_t': 1644187729.0626383, 'ip': '192.168.124.210', 'route': 'http://printwatch-printpal.pythonanywhere.com', 'nms': False, 'id': 'WY6C4bnCj621PaePuXQYBXCpPbAmFNB2', 'bad_responses': 16}
```

There isn't an error code 215 [documented](https://printpal.io/documentation/api/) - any idea what's going wrong here?

**Comment by printpal-io** [comment]
> I noticed that the PrintWatch tab is empty and a failed print wasn't correctly aborted.
> 
> When I looked through logs, I found the following:
> 
> ```
> .octoprint/logs/octoprint.log.2022-02-06:2022-02-07 09:48:49,062 - octoprint.plugins.printwatch - INFO - Response: {'response': 'Issue with payload data', 'statusCode': 215}
> .octoprint/logs/octoprint.log.2022-02-06:2022-02-07 09:48:59,933 - octoprint.plugins.printwatch - INFO - Payload: {'api_key': 'XXX', 'enable_shutoff': True, 'stream_url': 'http://192.168.124.210/webcam/?action=stream'} {'last_t': 1644187729.0626383, 'ip': '192.168.124.210', 'route': 'http://printwatch-printpal.pythonanywhere.com', 'nms': False, 'id': 'WY6C4bnCj621PaePuXQYBXCpPbAmFNB2', 'bad_responses': 16}
> ```
> 
> There isn't an error code 215 [documented](https://printpal.io/documentation/api/) - any idea what's going wrong here?

This issue is related to the inference request data structure not containing all of the required fields. Add an email to the settings, this can be any placeholder value. Additionally, alter the confidence threshold to another value other than the default and save the settings.

Additionally, the error code table has been updated here: https://printpal.io/documentation/api/

You should no longer be experiencing this issue with the update that we just pushed to the server, regardless of if you change your settings.

**Comment by printpal-io** [comment]
This issue has been fixed.
